PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0

EUNOIA_CODENAME := Aurora
EUNOIA_SEPARATOR := |

ifeq ($(EUNOIA_VERSION_APPEND_TIME_OF_DAY),true)
    EUNOIA_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    EUNOIA_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set EUNOIA_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef EUNOIA_BUILDTYPE
    EUNOIA_BUILDTYPE := EXPERIMENTAL
endif

EUNOIA_VERSION_SUFFIX := $(EUNOIA_BUILD_DATE)-$(EUNOIA_BUILD)

# Internal version
EUNOIA_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) $(EUNOIA_SEPARATOR) $(EUNOIA_CODENAME)
EUNOIA_ZIP_VERSION := $(shell echo '$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(EUNOIA_CODENAME)' | tr '[:upper:]' '[:lower:]')-$(EUNOIA_VERSION_SUFFIX)

# Display version
EUNOIA_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) $(EUNOIA_SEPARATOR) $(EUNOIA_BUILD) $(EUNOIA_SEPARATOR) $(EUNOIA_BUILDTYPE)
