PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0
PRODUCT_VERSION_CODENAME = Aurora

ifeq ($(EUNOIA_VERSION_APPEND_TIME_OF_DAY),true)
    EUNOIA_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    EUNOIA_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set EUNOIA_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef EUNOIA_BUILDTYPE
    EUNOIA_BUILDTYPE := COMMUNITY
endif

EUNOIA_VERSION_SUFFIX := $(EUNOIA_BUILD_DATE)-$(EUNOIA_BUILD)

# Internal version
EUNOIA_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) | $(PRODUCT_VERSION_CODENAME)
EUNOIA_ZIP_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(PRODUCT_VERSION_CODENAME)-$(EUNOIA_VERSION_SUFFIX)

# Display version
EUNOIA_DISPLAY_VERSION := $(EUNOIA_VERSION) | $(EUNOIA_BUILDTYPE)
